// <auto-generated />
using Carbon_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Carbon_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190617075259_TileModel")]
    partial class TileModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Carbon_API.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Money");

                    b.Property<string>("Name");

                    b.Property<int>("Xp");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Carbon_API.Models.Tile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("army");

                    b.Property<string>("description");

                    b.Property<string>("info");

                    b.Property<int>("money");

                    b.Property<int>("type");

                    b.HasKey("Id");

                    b.ToTable("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
